### ISSUE TITLE
Load buffers from Project

### ISSUE THREAD

**Issue by GRVYDEV** [sathishmanohar/quick-buffer-jump#1]
Hey great plugin! Would it be possible to load buffers that are already open on startup? I use [project.nvim](https://github.com/ahmedkhalf/project.nvim) and it seems that when I restart nvim it doesn't pick up my buffers that are already open.

**Comment by sathishmanohar** [comment]
Hey thanks! I don't restart nvim as a part of my workflow. I'm trying to replicate the bug. Is restarting part of project.nvim?

Could you please share the steps to reproduce the bug?
