### ISSUE TITLE
Add an option to truncate working directory to one or two levels

### ISSUE THREAD

**Issue by fakeharxy** [sathishmanohar/quick-buffer-jump#5]
Hi, excellent plug in, nice one!

Would it be possible to have a setting to lower the level of directories you can see in the buffer window? Currently I have something like

`MyComputer/work_projects/administrative/TonalApp/app/services/my_service.rb`

when really all I need is

`services/my_service.rb`

Thanks!

**Comment by sathishmanohar** [comment]
Hi Thanks!

I thought about this. Truncating directories might be useful in some cases but often times projects have files in multiple depths so truncating might lead to undesirable UX. One workaround could be to display just the file name but there could be multiple files with the same name under different directories as well which could cause confusion.

This is why we are currently displaying the whole path but I am open to this if there is a good solution that covers most of the use cases.
